version: "3"

services:
  # Сервис для базы данных MySQL
  db:
    image: mysql:latest
    container_name: mysql-db-study
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: geobud
    ports:
      - "3307:3306"
    volumes:
    - db-data:/var/lib/mysql

  # Сервис для phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql-db-study-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "8081:80"
    depends_on:
    - db

volumes:
  db-data: